__title__ = 'Payments control'
__description__ = 'helps to handle payment queries'
__url__ = 'https://github.com/VShkaberda/Payments_contol'
__version__ = '0.1.0'
__author__ = 'Shkaberda V.'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2019 Shkaberda Vadim'